-- Supabase / PostgreSQL — data_NF.md 정규화 스키마
-- SQL Editor에서 한 번에 실행 가능. 기존 public 동명 객체가 있으면 DROP 후 실행하거나 스키마만 분리하세요.

-- ---------------------------------------------------------------------------
-- 공통: updated_at
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.set_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at := now();
  RETURN NEW;
END;
$$;

-- ---------------------------------------------------------------------------
-- 룩업 (코드 마스터)
-- ---------------------------------------------------------------------------
CREATE TABLE public.account_statuses (
  code text PRIMARY KEY,
  display_name text
);

CREATE TABLE public.source_categories (
  code text PRIMARY KEY,
  display_name text
);

CREATE TABLE public.analysis_types (
  code text PRIMARY KEY,
  display_name text
);

CREATE TABLE public.chart_types (
  code text PRIMARY KEY,
  display_name text
);

CREATE TABLE public.aggregation_methods (
  code text PRIMARY KEY,
  display_name text
);

CREATE TABLE public.property_types (
  code text PRIMARY KEY,
  display_name text
);

CREATE TABLE public.etl_statuses (
  code text PRIMARY KEY,
  display_name text
);

CREATE TABLE public.etl_sources (
  code text PRIMARY KEY,
  display_name text
);

CREATE TABLE public.forecast_model_types (
  code text PRIMARY KEY,
  display_name text
);

-- ---------------------------------------------------------------------------
-- 데이터셋 · 지표 (metrics: dataset_code + code 복합 PK)
-- ---------------------------------------------------------------------------
CREATE TABLE public.datasets (
  code text PRIMARY KEY,
  source_category_code text NOT NULL REFERENCES public.source_categories (code),
  display_name text
);

CREATE TABLE public.metrics (
  dataset_code text NOT NULL REFERENCES public.datasets (code) ON DELETE CASCADE,
  code text NOT NULL,
  default_label text,
  PRIMARY KEY (dataset_code, code)
);

-- ---------------------------------------------------------------------------
-- 지역
-- ---------------------------------------------------------------------------
CREATE TABLE public.regions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  parent_region_id bigint REFERENCES public.regions (id) ON DELETE SET NULL,
  level smallint NOT NULL DEFAULT 1,
  name text NOT NULL,
  admin_code text UNIQUE
);

CREATE INDEX idx_regions_parent ON public.regions (parent_region_id);

-- ---------------------------------------------------------------------------
-- 유저 · 인증
-- ---------------------------------------------------------------------------
CREATE TABLE public.users (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email text NOT NULL UNIQUE,
  nickname text,
  password_hash text NOT NULL,
  status_code text NOT NULL REFERENCES public.account_statuses (code),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX idx_users_status ON public.users (status_code);

CREATE TRIGGER trg_users_updated_at
  BEFORE UPDATE ON public.users
  FOR EACH ROW EXECUTE PROCEDURE public.set_updated_at();

CREATE TABLE public.auth_sessions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL REFERENCES public.users (id) ON DELETE CASCADE,
  token_hash text NOT NULL UNIQUE,
  created_at timestamptz NOT NULL DEFAULT now(),
  expires_at timestamptz NOT NULL
);

CREATE INDEX idx_auth_sessions_user_id ON public.auth_sessions (user_id);
CREATE INDEX idx_auth_sessions_expires_at ON public.auth_sessions (expires_at);

-- ---------------------------------------------------------------------------
-- 워드클라우드 차원
-- ---------------------------------------------------------------------------
CREATE TABLE public.wordcloud_region_scopes (
  code text PRIMARY KEY,
  display_name text
);

CREATE TABLE public.wordcloud_categories (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code text NOT NULL UNIQUE,
  display_name text
);

CREATE TABLE public.wordcloud_subcategories (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  category_id bigint NOT NULL REFERENCES public.wordcloud_categories (id) ON DELETE CASCADE,
  code text NOT NULL,
  display_name text,
  UNIQUE (category_id, code)
);

CREATE TABLE public.keyword_terms (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  term_text text NOT NULL,
  category_id bigint NOT NULL REFERENCES public.wordcloud_categories (id) ON DELETE RESTRICT,
  subcategory_id bigint REFERENCES public.wordcloud_subcategories (id) ON DELETE SET NULL,
  wc_region_code text NOT NULL REFERENCES public.wordcloud_region_scopes (code)
);

CREATE INDEX idx_keyword_terms_category ON public.keyword_terms (category_id);
CREATE INDEX idx_keyword_terms_region ON public.keyword_terms (wc_region_code);

CREATE TABLE public.keyword_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  keyword_term_id bigint NOT NULL REFERENCES public.keyword_terms (id) ON DELETE CASCADE,
  source_code text NOT NULL REFERENCES public.etl_sources (code),
  event_date date,
  count_value integer NOT NULL DEFAULT 0
);

CREATE INDEX idx_keyword_events_term ON public.keyword_events (keyword_term_id);
CREATE INDEX idx_keyword_events_date ON public.keyword_events (event_date);

CREATE TABLE public.wordcloud_agg (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  keyword_term_id bigint NOT NULL REFERENCES public.keyword_terms (id) ON DELETE CASCADE,
  aggregation_date date,
  count_value integer NOT NULL DEFAULT 0,
  weight numeric NOT NULL DEFAULT 0,
  UNIQUE (keyword_term_id, aggregation_date)
);

CREATE INDEX idx_wordcloud_agg_date ON public.wordcloud_agg (aggregation_date);

-- 빠른 조회용 캐시 (data_NF.md: 정규형 완화)
CREATE TABLE public.wordcloud_terms (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  category_code text NOT NULL REFERENCES public.wordcloud_categories (code),
  wc_region_code text NOT NULL REFERENCES public.wordcloud_region_scopes (code),
  term_text text NOT NULL,
  weight numeric NOT NULL DEFAULT 0,
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TRIGGER trg_wordcloud_terms_updated_at
  BEFORE UPDATE ON public.wordcloud_terms
  FOR EACH ROW EXECUTE PROCEDURE public.set_updated_at();

-- ---------------------------------------------------------------------------
-- 서비스 스냅샷 · ETL
-- ---------------------------------------------------------------------------
CREATE TABLE public.analysis_snapshots (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  page text NOT NULL UNIQUE,
  line jsonb,
  bar jsonb,
  donut jsonb,
  accents jsonb,
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TRIGGER trg_analysis_snapshots_updated_at
  BEFORE UPDATE ON public.analysis_snapshots
  FOR EACH ROW EXECUTE PROCEDURE public.set_updated_at();

CREATE TABLE public.etl_runs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  source_code text NOT NULL REFERENCES public.etl_sources (code),
  status_code text NOT NULL REFERENCES public.etl_statuses (code),
  details text,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX idx_etl_runs_created_at ON public.etl_runs (created_at DESC);

-- ---------------------------------------------------------------------------
-- 유저 분석
-- ---------------------------------------------------------------------------
CREATE TABLE public.user_analyses (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL REFERENCES public.users (id) ON DELETE CASCADE,
  analysis_type_code text NOT NULL REFERENCES public.analysis_types (code),
  title text NOT NULL,
  dataset_code text NOT NULL REFERENCES public.datasets (code),
  metric_code text NOT NULL,
  aggregation_method_code text NOT NULL REFERENCES public.aggregation_methods (code),
  group_by_field text,
  chart_type_code text NOT NULL REFERENCES public.chart_types (code),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  FOREIGN KEY (dataset_code, metric_code) REFERENCES public.metrics (dataset_code, code)
);

CREATE INDEX idx_user_analyses_user_id ON public.user_analyses (user_id);

CREATE TRIGGER trg_user_analyses_updated_at
  BEFORE UPDATE ON public.user_analyses
  FOR EACH ROW EXECUTE PROCEDURE public.set_updated_at();

CREATE TABLE public.user_analysis_filters (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  analysis_id bigint NOT NULL REFERENCES public.user_analyses (id) ON DELETE CASCADE,
  field_code text NOT NULL,
  operator text NOT NULL,
  value_text text,
  value_num numeric,
  sort_order integer NOT NULL DEFAULT 0
);

CREATE INDEX idx_user_analysis_filters_analysis ON public.user_analysis_filters (analysis_id);

CREATE TABLE public.user_analysis_results (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  analysis_id bigint NOT NULL REFERENCES public.user_analyses (id) ON DELETE CASCADE,
  result_version integer NOT NULL DEFAULT 1,
  result_json jsonb,
  summary_text text,
  generated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX idx_user_analysis_results_analysis ON public.user_analysis_results (analysis_id);

CREATE TABLE public.user_analysis_chart_series (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  analysis_result_id bigint NOT NULL REFERENCES public.user_analysis_results (id) ON DELETE CASCADE,
  series_name text,
  x_date date,
  x_text text,
  y_value numeric,
  series_order integer NOT NULL DEFAULT 0
);

CREATE INDEX idx_user_analysis_chart_series_result ON public.user_analysis_chart_series (analysis_result_id);

CREATE TABLE public.user_analysis_table_rows (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  analysis_result_id bigint NOT NULL REFERENCES public.user_analysis_results (id) ON DELETE CASCADE,
  row_order integer NOT NULL DEFAULT 0,
  row_json jsonb
);

CREATE INDEX idx_user_analysis_table_rows_result ON public.user_analysis_table_rows (analysis_result_id);

CREATE TABLE public.saved_builder_analyses (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL REFERENCES public.users (id) ON DELETE CASCADE,
  title text NOT NULL,
  keyword text,
  dataset_code text NOT NULL REFERENCES public.datasets (code),
  metric_code text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  FOREIGN KEY (dataset_code, metric_code) REFERENCES public.metrics (dataset_code, code)
);

CREATE INDEX idx_saved_builder_analyses_user ON public.saved_builder_analyses (user_id);

-- ---------------------------------------------------------------------------
-- 원본 데이터
-- ---------------------------------------------------------------------------
CREATE TABLE public.real_estate_transactions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  region_id bigint NOT NULL REFERENCES public.regions (id),
  property_type_code text NOT NULL REFERENCES public.property_types (code),
  deal_date date,
  area_m2 numeric,
  sale_price numeric,
  rent_price numeric,
  floor integer,
  build_year integer,
  source_code text NOT NULL REFERENCES public.etl_sources (code),
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX idx_real_estate_region ON public.real_estate_transactions (region_id);
CREATE INDEX idx_real_estate_deal_date ON public.real_estate_transactions (deal_date);

CREATE TABLE public.population_stats (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  region_id bigint NOT NULL REFERENCES public.regions (id),
  period_start date NOT NULL,
  period_end date NOT NULL,
  dataset_code text NOT NULL,
  metric_code text NOT NULL,
  value numeric NOT NULL,
  source_code text NOT NULL REFERENCES public.etl_sources (code),
  created_at timestamptz NOT NULL DEFAULT now(),
  FOREIGN KEY (dataset_code, metric_code) REFERENCES public.metrics (dataset_code, code)
);

CREATE INDEX idx_population_stats_region ON public.population_stats (region_id);

CREATE TABLE public.traffic_stats (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  region_id bigint NOT NULL REFERENCES public.regions (id),
  period_start date NOT NULL,
  period_end date NOT NULL,
  dataset_code text NOT NULL,
  metric_code text NOT NULL,
  value numeric NOT NULL,
  source_code text NOT NULL REFERENCES public.etl_sources (code),
  created_at timestamptz NOT NULL DEFAULT now(),
  FOREIGN KEY (dataset_code, metric_code) REFERENCES public.metrics (dataset_code, code)
);

CREATE INDEX idx_traffic_stats_region ON public.traffic_stats (region_id);

-- ---------------------------------------------------------------------------
-- 예측
-- ---------------------------------------------------------------------------
CREATE TABLE public.forecast_runs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  analysis_id bigint NOT NULL REFERENCES public.user_analyses (id) ON DELETE CASCADE,
  model_type_code text NOT NULL REFERENCES public.forecast_model_types (code),
  train_start_date date,
  train_end_date date,
  prediction_start_date date,
  prediction_end_date date,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX idx_forecast_runs_analysis ON public.forecast_runs (analysis_id);

CREATE TABLE public.forecast_metric_entries (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  forecast_run_id bigint NOT NULL REFERENCES public.forecast_runs (id) ON DELETE CASCADE,
  metric_key text NOT NULL,
  metric_value numeric NOT NULL,
  UNIQUE (forecast_run_id, metric_key)
);

CREATE TABLE public.forecast_points (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  forecast_run_id bigint NOT NULL REFERENCES public.forecast_runs (id) ON DELETE CASCADE,
  target_date date NOT NULL,
  actual_value numeric,
  predicted_value numeric,
  lower_bound numeric,
  upper_bound numeric
);

CREATE INDEX idx_forecast_points_run ON public.forecast_points (forecast_run_id);

-- ---------------------------------------------------------------------------
-- 최소 시드 (FK 검증용 — 운영 코드에 맞게 수정)
-- ---------------------------------------------------------------------------
INSERT INTO public.account_statuses (code, display_name) VALUES
  ('active', '활성'), ('inactive', '비활성'), ('deleted', '삭제');

INSERT INTO public.source_categories (code, display_name) VALUES
  ('real_estate', '부동산');

INSERT INTO public.analysis_types (code, display_name) VALUES
  ('aggregation', '집계'), ('comparison', '비교'), ('prediction', '예측');

INSERT INTO public.chart_types (code, display_name) VALUES
  ('line', '라인'), ('bar', '바'), ('table', '표'), ('mixed', '혼합'), ('donut', '도넛');

INSERT INTO public.aggregation_methods (code, display_name) VALUES
  ('sum', '합계'), ('avg', '평균'), ('median', '중앙값'), ('count', '건수');

INSERT INTO public.property_types (code, display_name) VALUES
  ('apartment', '아파트'), ('officetel', '오피스텔');

INSERT INTO public.etl_statuses (code, display_name) VALUES
  ('success', '성공'), ('failed', '실패'), ('running', '실행중');

INSERT INTO public.etl_sources (code, display_name) VALUES
  ('default', '기본'), ('news', '뉴스'), ('internal_etl', '내부 ETL');

INSERT INTO public.forecast_model_types (code, display_name) VALUES
  ('arima', 'ARIMA'), ('prophet', 'Prophet'), ('xgboost', 'XGBoost'), ('lstm', 'LSTM');

INSERT INTO public.datasets (code, source_category_code, display_name) VALUES
  ('apartment_trade_price', 'real_estate', '아파트 매매가');

INSERT INTO public.metrics (dataset_code, code, default_label) VALUES
  ('apartment_trade_price', 'sale_price', '매매가'),
  ('apartment_trade_price', 'rent_price', '전월세');

INSERT INTO public.wordcloud_region_scopes (code, display_name) VALUES
  ('kr', '한국'), ('global', '글로벌');

INSERT INTO public.wordcloud_categories (code, display_name) VALUES
  ('agri', '농업'),
  ('health', '건강');

-- ---------------------------------------------------------------------------
-- RLS: 필요 시 Supabase에서 테이블별로 ENABLE ROW LEVEL SECURITY 및 정책 추가
-- ---------------------------------------------------------------------------
