-- Supabase / PostgreSQL 스키마 (data.md 기준)
-- SQL Editor에서 위에서 아래 순으로 실행하거나, 한 번에 실행 가능합니다.

-- ---------------------------------------------------------------------------
-- 공통: updated_at 자동 갱신
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.set_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at := now();
  RETURN NEW;
END;
$$;

-- ---------------------------------------------------------------------------
-- 1. 유저 및 인증
-- ---------------------------------------------------------------------------
CREATE TABLE public.users (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email text NOT NULL UNIQUE,
  nickname text,
  password_hash text NOT NULL,
  status text NOT NULL DEFAULT 'active'
    CHECK (status IN ('active', 'inactive', 'deleted')),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX idx_users_status ON public.users (status);

CREATE TRIGGER trg_users_updated_at
  BEFORE UPDATE ON public.users
  FOR EACH ROW EXECUTE PROCEDURE public.set_updated_at();

CREATE TABLE public.auth_sessions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL REFERENCES public.users (id) ON DELETE CASCADE,
  token_hash text NOT NULL UNIQUE,
  created_at timestamptz NOT NULL DEFAULT now(),
  expires_at timestamptz NOT NULL
);

CREATE INDEX idx_auth_sessions_user_id ON public.auth_sessions (user_id);
CREATE INDEX idx_auth_sessions_expires_at ON public.auth_sessions (expires_at);

-- ---------------------------------------------------------------------------
-- 2. 메인 서비스 데이터 (스냅샷 / 워드클라우드 / 저장 분석 / ETL)
-- ---------------------------------------------------------------------------
CREATE TABLE public.analysis_snapshots (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  page text NOT NULL UNIQUE,
  line jsonb,
  bar jsonb,
  donut jsonb,
  accents jsonb,
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TRIGGER trg_analysis_snapshots_updated_at
  BEFORE UPDATE ON public.analysis_snapshots
  FOR EACH ROW EXECUTE PROCEDURE public.set_updated_at();

CREATE TABLE public.wordcloud_terms (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  category text NOT NULL,
  region text NOT NULL,
  text text NOT NULL,
  weight numeric NOT NULL DEFAULT 0,
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TRIGGER trg_wordcloud_terms_updated_at
  BEFORE UPDATE ON public.wordcloud_terms
  FOR EACH ROW EXECUTE PROCEDURE public.set_updated_at();

CREATE TABLE public.saved_builder_analyses (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL REFERENCES public.users (id) ON DELETE CASCADE,
  title text NOT NULL,
  keyword text,
  metric text,
  metric_label text,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX idx_saved_builder_analyses_user_id ON public.saved_builder_analyses (user_id);

CREATE TABLE public.etl_runs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  source text NOT NULL,
  status text NOT NULL,
  details text,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX idx_etl_runs_created_at ON public.etl_runs (created_at DESC);

-- ---------------------------------------------------------------------------
-- 3. 유저 분석 (정의 / 결과 / 차트 시리즈 / 표 행)
-- ---------------------------------------------------------------------------
CREATE TABLE public.user_analyses (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL REFERENCES public.users (id) ON DELETE CASCADE,
  analysis_type text NOT NULL,
  title text NOT NULL,
  source_category text,
  dataset_name text,
  metric_name text,
  aggregation_method text,
  group_by_field text,
  filter_json jsonb,
  chart_type text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX idx_user_analyses_user_id ON public.user_analyses (user_id);

CREATE TRIGGER trg_user_analyses_updated_at
  BEFORE UPDATE ON public.user_analyses
  FOR EACH ROW EXECUTE PROCEDURE public.set_updated_at();

CREATE TABLE public.user_analysis_results (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  analysis_id bigint NOT NULL REFERENCES public.user_analyses (id) ON DELETE CASCADE,
  result_version integer NOT NULL DEFAULT 1,
  result_json jsonb,
  summary_text text,
  generated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX idx_user_analysis_results_analysis_id ON public.user_analysis_results (analysis_id);

CREATE TABLE public.user_analysis_chart_series (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  analysis_result_id bigint NOT NULL REFERENCES public.user_analysis_results (id) ON DELETE CASCADE,
  series_name text,
  x_value text,
  y_value numeric,
  series_order integer NOT NULL DEFAULT 0
);

CREATE INDEX idx_user_analysis_chart_series_result_id ON public.user_analysis_chart_series (analysis_result_id);

CREATE TABLE public.user_analysis_table_rows (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  analysis_result_id bigint NOT NULL REFERENCES public.user_analysis_results (id) ON DELETE CASCADE,
  row_order integer NOT NULL DEFAULT 0,
  row_json jsonb
);

CREATE INDEX idx_user_analysis_table_rows_result_id ON public.user_analysis_table_rows (analysis_result_id);

-- ---------------------------------------------------------------------------
-- 4. 원본 데이터 (부동산 거래 예시)
-- ---------------------------------------------------------------------------
CREATE TABLE public.real_estate_transactions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  region_large text,
  region_mid text,
  region_small text,
  property_type text,
  deal_date date,
  area_m2 numeric,
  sale_price numeric,
  rent_price numeric,
  floor integer,
  build_year integer,
  source_name text,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX idx_real_estate_deal_date ON public.real_estate_transactions (deal_date);
CREATE INDEX idx_real_estate_region_mid ON public.real_estate_transactions (region_mid);

-- ---------------------------------------------------------------------------
-- 5. 예측
-- ---------------------------------------------------------------------------
CREATE TABLE public.forecast_runs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  analysis_id bigint NOT NULL REFERENCES public.user_analyses (id) ON DELETE CASCADE,
  model_type text NOT NULL,
  train_start_date date,
  train_end_date date,
  prediction_start_date date,
  prediction_end_date date,
  metrics_json jsonb,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX idx_forecast_runs_analysis_id ON public.forecast_runs (analysis_id);

CREATE TABLE public.forecast_points (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  forecast_run_id bigint NOT NULL REFERENCES public.forecast_runs (id) ON DELETE CASCADE,
  target_date date NOT NULL,
  actual_value numeric,
  predicted_value numeric,
  lower_bound numeric,
  upper_bound numeric
);

CREATE INDEX idx_forecast_points_run_id ON public.forecast_points (forecast_run_id);

-- ---------------------------------------------------------------------------
-- 6. 워드클라우드 확장
-- ---------------------------------------------------------------------------
CREATE TABLE public.keyword_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  category text NOT NULL,
  sub_category text,
  keyword text NOT NULL,
  source_name text,
  event_date date,
  count_value integer NOT NULL DEFAULT 0
);

CREATE INDEX idx_keyword_events_event_date ON public.keyword_events (event_date);

CREATE TABLE public.wordcloud_agg (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  category text NOT NULL,
  sub_category text,
  keyword text NOT NULL,
  count_value integer NOT NULL DEFAULT 0,
  weight numeric NOT NULL DEFAULT 0,
  aggregation_date date
);

CREATE INDEX idx_wordcloud_agg_aggregation_date ON public.wordcloud_agg (aggregation_date);

-- ---------------------------------------------------------------------------
-- Row Level Security (RLS)는 프로젝트 정책에 맞게 켜고 정책을 추가하세요.
-- 예: ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
-- ---------------------------------------------------------------------------
